# Generated by Django 5.0.1 on 2024-01-13 23:24

import aluraflix.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aluraflix', '0002_category_alter_video_description_video_category_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='category_id',
            field=models.ForeignKey(default=aluraflix.models.get_default_categoty, on_delete=django.db.models.deletion.CASCADE, to='aluraflix.category'),
        ),
    ]
